### ISSUE TITLE
 CAGEexp from imported bam file

### ISSUE THREAD

**Issue by ewong159** [charles-plessy/CAGEr#35] opened 2021-01-11 20:12 UTC
Hi, I would like to create CAGEexp from imported bam file. 

input.file <- CAGEr:::import.bam("501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam", "bam", sequencingQualityThreshold = 10, mappingQualityThreshold = 20)

> CAGEr:::import.bam("501_shLUC_6D_1_CAGE_trimmed_hg19_Aligned.sortedByCoord.out.bam", "bam", sequencingQualityThreshold = 10, mappingQualityThreshold = 20)
	-> Filtering out low quality reads...
GRanges object with 1212937 ranges and 3 metadata columns:
              seqnames        ranges strand |                     seq                    qual read.length
                 <Rle>     <IRanges>  <Rle> |          <DNAStringSet>          <PhredQuality>   <integer>
        [1]          1   20095-20137      - | AAACAGAGAG...GCGGTGAGTC EEEEEEEEEE...EEEEEEEEEE          43
        [2]          1   56238-56280      - | CTGGCTGGCC...CTAGATTCTC EEEEEEEEEE...EEEEEEEEEE          43
        [3]          1 353309-564634      - | ACAAACCACC...ACATATTTTG </A/////A/...EEEEEAEEEE          43
        [4]          1 565287-565329      + | ACCAATCAAT...GCTATAGCAA EEEEEEEEEE...EEEEEEEEEE          43
        [5]          1 565288-565330      + | CCAATCAATA...CTATAGCAAT EEEEEEEEEE...EEEEEEEEEE          43

myCAGEset <- CAGEexp(genomeName = "BSgenome.Hsapiens.UCSC.hg19",inputFiles = input.file, inputFilesType = "bam", sampleLabels = c("labels"))

Error in `rownames<-`(`*tmp*`, value = "labels") : 
  invalid rownames length

How should l specify the rowname?

Thanks.
Elissa

**Comment by charles-plessy** [comment] 2021-01-12 01:51
Closed duplicate of issue #34

**Closed by charles-plessy** 2021-01-12 01:51 UTC
